using System.Text.Json.Serialization;

namespace DataHarvester.Models;

public class SpotifyArtistResponse
{
    [JsonPropertyName("artists")]
    public ArtistsContainer Artists { get; set; }
}
public class ArtistsContainer
{
    [JsonPropertyName("items")]
    public List<SpotifyArtist> Items { get; set; }
}

//autogenerated from Json
public class SpotifyArtist
{
    [JsonPropertyName("external_urls")]
    public required ExternalUrls ExternalUrls { get; set; }

    [JsonPropertyName("followers")]
    public required Followers Followers { get; set; }

    [JsonPropertyName("genres")]
    public required List<string> Genres { get; set; }

    [JsonPropertyName("href")]
    public required string Href { get; set; }

    [JsonPropertyName("id")]
    public required string Id { get; set; }

    [JsonPropertyName("images")]
    public required List<Image> Images { get; set; }

    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("popularity")]
    public int Popularity { get; set; }

    [JsonPropertyName("type")]
    public required string Type { get; set; }

    [JsonPropertyName("uri")]
    public required string Uri { get; set; }
}


public record ExternalUrls
{
    [JsonPropertyName("spotify")]
    public required string spotify { get; set; }
}

public record Followers
{
    [JsonPropertyName("href")]
    public required object href { get; set; }

    [JsonPropertyName("total")]
    public int total { get; set; }
}

public record Image
{
    [JsonPropertyName("url")]
    public string url { get; set; }

    [JsonPropertyName("height")]
    public int height { get; set; }

    [JsonPropertyName("width")]
    public int width { get; set; }
}

public record Root
{
    [JsonPropertyName("external_urls")]
    public ExternalUrls external_urls { get; set; }

    [JsonPropertyName("followers")]
    public Followers followers { get; set; }

    [JsonPropertyName("genres")]
    public List<object> genres { get; set; }

    [JsonPropertyName("href")]
    public string href { get; set; }

    [JsonPropertyName("id")]
    public string id { get; set; }

    [JsonPropertyName("images")]
    public List<Image> images { get; set; }

    [JsonPropertyName("name")]
    public string name { get; set; }

    [JsonPropertyName("popularity")]
    public int popularity { get; set; }

    [JsonPropertyName("type")]
    public string type { get; set; }

    [JsonPropertyName("uri")]
    public string uri { get; set; }
}